sudo: required
services:
  - docker

before_install:
  - docker build -t escanorsama/multidocker -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true escanorsama/multidocker npm test

after_success:
  - docker build -t escanorsama/multi-client ./client
  - docker build -t escanorsama/multi-nginx ./nginx
  - docker build -t escanorsama/multi-server ./server
  - docker build -t escanorsama/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push escanorsama/multi-client
  - docker push escanorsama/multi-nginx
  - docker push escanorsama/multi-server
  - docker push escanorsama/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-east-2-073344608916'
  bucket_path: 'docker-multi'
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
